/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/tenants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Tenants
         * @description List every tenant.
         *
         *     Not filtered by principal: authorisation for this UI is the allow-list in
         *     the settings, and someone who may use it at all may see the tenants. A
         *     per-tenant permission model would be a second authorisation system with
         *     one user in it.
         */
        get: operations["list_tenants_api_v1_tenants_get"];
        put?: never;
        /**
         * Create Tenant
         * @description Create a tenant.
         *
         *     A duplicate key is a 409 rather than an integrity error reaching the
         *     client: `Tenant.key` is unique, and re-creating one is a plausible mistake
         *     rather than a broken request.
         */
        post: operations["create_tenant_api_v1_tenants_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenants/{tenant_id}/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Audit
         * @description List the tenant's audit entries, optionally filtered.
         *
         *     `template` filters by template id. `from_`/`to` bound `ts`. Results are
         *     ordered newest first. `limit` (default 100, max 1000) and `offset`
         *     (default 0) bound and page the result set -- the audit table grows
         *     with every render, so an unbounded query here would eventually scan
         *     and return the tenant's entire history. Plain limit/offset is enough
         *     for now; cursor-based pagination is a separate follow-up if callers
         *     ever need to page deep, stable result sets.
         */
        get: operations["list_audit_api_v1_tenants__tenant_id__audit_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenants/{tenant_id}/clients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Clients
         * @description List a tenant's API clients, without their tokens.
         */
        get: operations["list_clients_api_v1_tenants__tenant_id__clients_get"];
        put?: never;
        /**
         * Create Client
         * @description Create an API client and return its token, once.
         *
         *     One client per calling service rather than one shared between them: a
         *     compromised service is then revoked on its own, and `audit_log` says which
         *     service rendered. A shared token names the same caller four times.
         */
        post: operations["create_client_api_v1_tenants__tenant_id__clients_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenants/{tenant_id}/clients/{client_id}/revoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Revoke Client
         * @description Deactivate an API client.
         *
         *     Deactivated rather than deleted: `audit_log` rows reference the client
         *     that made each request, and a deleted row turns a year of history into
         *     unattributable entries.
         */
        post: operations["revoke_client_api_v1_tenants__tenant_id__clients__client_id__revoke_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenants/{tenant_id}/credentials": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Credentials
         * @description List the tenant's credential sets, metadata only.
         */
        get: operations["list_credentials_api_v1_tenants__tenant_id__credentials_get"];
        put?: never;
        /**
         * Create Credential
         * @description Create a credential set by generating or importing key material.
         *
         *     Apple either generates a fresh key from `common_name`, or imports an
         *     existing pair from `private_key` + `certificate`. Google requires
         *     `issuer_id` and `service_account_json`. A missing combination is a
         *     `400 invalid_request`.
         */
        post: operations["create_credential_api_v1_tenants__tenant_id__credentials_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenants/{tenant_id}/credentials/{credential_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Revoke Credential
         * @description Mark a credential set `revoked`. Never a hard delete.
         */
        delete: operations["revoke_credential_api_v1_tenants__tenant_id__credentials__credential_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenants/{tenant_id}/credentials/{credential_id}/certificate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Install Certificate
         * @description Install the signed certificate, activating a pending Apple credential set.
         */
        put: operations["install_certificate_api_v1_tenants__tenant_id__credentials__credential_id__certificate_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenants/{tenant_id}/credentials/{credential_id}/csr": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Csr
         * @description Return the stored CSR in PEM. The CSR is public, never secret.
         */
        get: operations["get_csr_api_v1_tenants__tenant_id__credentials__credential_id__csr_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenants/{tenant_id}/credentials/{credential_id}/renew": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Renew Credential
         * @description Create a successor Apple credential set with a fresh keypair and CSR.
         */
        post: operations["renew_credential_api_v1_tenants__tenant_id__credentials__credential_id__renew_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenants/{tenant_id}/fields": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Fields
         * @description Return the cached data_provider field catalogue.
         */
        get: operations["list_fields_api_v1_tenants__tenant_id__fields_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenants/{tenant_id}/fields/catalogue.json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export Catalogue
         * @description Return the catalogue in the shape `edutap.pass_designer` loads.
         *
         *     THE SAME CATALOGUE, NOT A SECOND ONE. The designer lays a pass out against
         *     a field list and this service validates every mapping rule against one; if
         *     those are two files, a rule authored in the designer fails at publish time
         *     and the difference is invisible until then. The designer ships a neutral
         *     example for development, and a deployment points it at this.
         *
         *     Deliberately the *cached* rows rather than a live call to the data
         *     provider: what a rule is validated against is this cache, so what the
         *     designer draws against has to be the same thing. `POST /fields/refresh` is
         *     what moves both.
         */
        get: operations["export_catalogue_api_v1_tenants__tenant_id__fields_catalogue_json_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenants/{tenant_id}/fields/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh Fields
         * @description Replace the cached catalogue from `data_provider` and return it.
         */
        post: operations["refresh_fields_api_v1_tenants__tenant_id__fields_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenants/{tenant_id}/templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Templates
         * @description List every template of the tenant.
         */
        get: operations["list_templates_api_v1_tenants__tenant_id__templates_get"];
        put?: never;
        /**
         * Create Template
         * @description Create a new template.
         */
        post: operations["create_template_api_v1_tenants__tenant_id__templates_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenants/{tenant_id}/templates/{template_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Template
         * @description Return one template.
         */
        get: operations["get_template_api_v1_tenants__tenant_id__templates__template_id__get"];
        put?: never;
        post?: never;
        /**
         * Archive Template
         * @description Archive a template. Never a hard delete.
         */
        delete: operations["archive_template_api_v1_tenants__tenant_id__templates__template_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update Template
         * @description Patch a template's name or description.
         */
        patch: operations["update_template_api_v1_tenants__tenant_id__templates__template_id__patch"];
        trace?: never;
    };
    "/api/v1/tenants/{tenant_id}/templates/{template_id}/variants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Variants
         * @description List every variant of a template.
         */
        get: operations["list_variants_api_v1_tenants__tenant_id__templates__template_id__variants_get"];
        put?: never;
        /**
         * Create Variant
         * @description Create a new variant under a template.
         */
        post: operations["create_variant_api_v1_tenants__tenant_id__templates__template_id__variants_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenants/{tenant_id}/variants/{variant_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Variant
         * @description Return one variant.
         */
        get: operations["get_variant_api_v1_tenants__tenant_id__variants__variant_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update Variant
         * @description Patch a variant, including `is_default` and `credential_set_id`.
         */
        patch: operations["update_variant_api_v1_tenants__tenant_id__variants__variant_id__patch"];
        trace?: never;
    };
    "/api/v1/tenants/{tenant_id}/variants/{variant_id}/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sync Variant
         * @description Push a Google variant's published class definition. Idempotent.
         *
         *     Validates the variant is Google-typed *before* touching any credential
         *     material -- a non-Google variant is rejected without ever opening or
         *     decrypting a credential set, since credentials only need to be decrypted
         *     once it is known a Google push is actually going to happen.
         */
        post: operations["sync_variant_api_v1_tenants__tenant_id__variants__variant_id__sync_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenants/{tenant_id}/variants/{variant_id}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Versions
         * @description List every version of a variant.
         */
        get: operations["list_versions_api_v1_tenants__tenant_id__variants__variant_id__versions_get"];
        put?: never;
        /**
         * Create Version
         * @description Create a draft version.
         *
         *     Apple: `multipart/form-data` with the `.pkpasstemplate` bundle as
         *     `file`. Google: a JSON body with `class_json` and `object_json`. The
         *     content type decides which path runs, since the two platforms need
         *     structurally different payloads.
         */
        post: operations["create_version_api_v1_tenants__tenant_id__variants__variant_id__versions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenants/{tenant_id}/versions/{version_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Version
         * @description Return one version.
         */
        get: operations["get_version_api_v1_tenants__tenant_id__versions__version_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenants/{tenant_id}/versions/{version_id}/assets/{filename}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Asset
         * @description Return one version's asset bytes.
         */
        get: operations["get_asset_api_v1_tenants__tenant_id__versions__version_id__assets__filename__get"];
        /**
         * Put Asset
         * @description Replace one draft version's asset. `409` once the version is published.
         */
        put: operations["put_asset_api_v1_tenants__tenant_id__versions__version_id__assets__filename__put"];
        post?: never;
        /**
         * Delete Asset
         * @description Remove one draft version's asset. `409` once the version is published.
         */
        delete: operations["delete_asset_api_v1_tenants__tenant_id__versions__version_id__assets__filename__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenants/{tenant_id}/versions/{version_id}/mappings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Mappings
         * @description Return a version's mapping rules.
         */
        get: operations["get_mappings_api_v1_tenants__tenant_id__versions__version_id__mappings_get"];
        /**
         * Set Mappings
         * @description Bulk replace a draft version's mapping rules. `409` once published.
         */
        put: operations["set_mappings_api_v1_tenants__tenant_id__versions__version_id__mappings_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenants/{tenant_id}/versions/{version_id}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Publish Version
         * @description Validate then publish a draft version, archiving its predecessor.
         */
        post: operations["publish_version_api_v1_tenants__tenant_id__versions__version_id__publish_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenants/{tenant_id}/versions/{version_id}/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Validate Version
         * @description Run full publish-time validation without publishing.
         */
        post: operations["validate_version_api_v1_tenants__tenant_id__versions__version_id__validate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Healthz
         * @description Report that the process is alive.
         */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readyz
         * @description Report readiness after checking database, object store and data provider.
         */
        get: operations["readyz_readyz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ApiClientCreated
         * @description An API client the moment it is created, with its token.
         *
         *     THE ONLY TIME THE TOKEN EXISTS IN READABLE FORM. Only its SHA-256 is
         *     stored, so this response is not repeatable: a token that is lost is
         *     replaced, not recovered. That is a property worth keeping -- a store that
         *     can show a token again is a store that can leak every token at once.
         */
        ApiClientCreated: {
            /** Active */
            active: boolean;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Scopes */
            scopes: string[];
            /** Token */
            token: string;
        };
        /**
         * ApiClientIn
         * @description An API client to create.
         */
        ApiClientIn: {
            /** Name */
            name: string;
            /** Scopes */
            scopes: components["schemas"]["Scope"][];
        };
        /**
         * ApiClientOut
         * @description An API client as the UI shows it -- never its token.
         */
        ApiClientOut: {
            /** Active */
            active: boolean;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Scopes */
            scopes: string[];
        };
        /**
         * AssetResponse
         * @description Response describing one stored template asset (metadata only).
         */
        AssetResponse: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Filename */
            filename: string;
            /** Media Type */
            media_type: string;
            /** Sha256 */
            sha256: string;
            /** Size */
            size: number;
        };
        /**
         * AuditEntryResponse
         * @description Response describing one audit log entry.
         */
        AuditEntryResponse: {
            /** Action */
            action: string;
            /** Actor Client Id */
            actor_client_id?: string | null;
            /** Actor Principal */
            actor_principal?: string | null;
            /** Duration Ms */
            duration_ms: number;
            /** Error Code */
            error_code?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Outcome */
            outcome: string;
            /** Request Id */
            request_id: string;
            /** Requested Fields */
            requested_fields: string[];
            /** Subject Ref */
            subject_ref?: string | null;
            /** Template Id */
            template_id?: string | null;
            /**
             * Ts
             * Format: date-time
             */
            ts: string;
            /** Variant Id */
            variant_id?: string | null;
            /** Version Id */
            version_id?: string | null;
            wallet_type?: components["schemas"]["WalletType"] | null;
        };
        /**
         * CatalogueExport
         * @description The field catalogue as `edutap.pass_designer` loads it.
         *
         *     A wrapper object rather than a bare list because that is the file the
         *     designer reads (`PASS_DESIGNER_CATALOGUE_PATH`), and a shape that has to be
         *     edited on the way over is a shape that will be edited wrongly once.
         */
        CatalogueExport: {
            /** Fields */
            fields: components["schemas"]["FieldResponse"][];
        };
        /**
         * CreateCredentialRequest
         * @description Request body to create, import or install a credential set.
         */
        CreateCredentialRequest: {
            /** Certificate */
            certificate?: string | null;
            /** Common Name */
            common_name?: string | null;
            /** Issuer Id */
            issuer_id?: string | null;
            /** Label */
            label: string;
            /** Private Key */
            private_key?: string | null;
            provider: components["schemas"]["Provider"];
            /** Service Account Json */
            service_account_json?: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * CreateTemplateRequest
         * @description Request body to create a new template.
         */
        CreateTemplateRequest: {
            /** Description */
            description?: string | null;
            /** Key */
            key: string;
            /** Name */
            name: string;
        };
        /**
         * CreateVariantRequest
         * @description Request body to create a new template variant.
         */
        CreateVariantRequest: {
            /** Credential Set Id */
            credential_set_id?: string | null;
            /** Google Class Id */
            google_class_id?: string | null;
            /**
             * Is Default
             * @default false
             */
            is_default: boolean;
            /** Key */
            key: string;
            /** Name */
            name: string;
            wallet_type: components["schemas"]["WalletType"];
        };
        /**
         * CredentialResponse
         * @description Metadata about a credential set.
         *
         *     Exposes only metadata -- never `private_key`, `service_account_json`,
         *     `ciphertext`, `nonce` or `wrapped_dek`. See the module docstring.
         */
        CredentialResponse: {
            /** Cert Fingerprint Sha256 */
            cert_fingerprint_sha256?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Issuer Id */
            issuer_id?: string | null;
            /** Label */
            label: string;
            /** Nfc Capable */
            nfc_capable?: boolean | null;
            /** Not After */
            not_after?: string | null;
            /** Not Before */
            not_before?: string | null;
            /** Organization Name */
            organization_name?: string | null;
            /** Pass Type Identifier */
            pass_type_identifier?: string | null;
            provider: components["schemas"]["Provider"];
            /** Service Account Email */
            service_account_email?: string | null;
            status: components["schemas"]["CredentialStatus"];
            /** Team Identifier */
            team_identifier?: string | null;
        };
        /**
         * CredentialStatus
         * @description Lifecycle state of a credential set.
         * @enum {string}
         */
        CredentialStatus: "key_pending" | "active" | "expired" | "revoked" | "superseded";
        /**
         * FieldResponse
         * @description Response describing one entry of the data-provider field catalogue.
         */
        FieldResponse: {
            /** Description */
            description?: string | null;
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Required */
            required: boolean;
            value_type: components["schemas"]["ValueType"];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * InstallCertificateRequest
         * @description Request body to install a signed certificate onto a pending credential.
         */
        InstallCertificateRequest: {
            /** Certificate Pem */
            certificate_pem: string;
        };
        /**
         * MappingRulesRequest
         * @description Request body to replace a draft version's mapping rules.
         */
        MappingRulesRequest: {
            /** Rules */
            rules: components["schemas"]["RuleSpec"][];
        };
        /**
         * MappingRulesResponse
         * @description Response listing a version's mapping rules.
         */
        MappingRulesResponse: {
            /** Rules */
            rules: components["schemas"]["RuleSpec"][];
        };
        /**
         * Provider
         * @description Credential provider.
         * @enum {string}
         */
        Provider: "apple" | "google";
        /**
         * RuleSpec
         * @description A single substitution rule, decoupled from the database row.
         */
        RuleSpec: {
            /** Default Value */
            default_value?: string | null;
            /**
             * Position
             * @default 0
             */
            position: number;
            /**
             * Required
             * @default true
             */
            required: boolean;
            /** Source Field */
            source_field: string;
            /** Target */
            target: string;
            target_kind: components["schemas"]["TargetKind"];
            value_type: components["schemas"]["ValueType"];
        };
        /**
         * Scope
         * @description API client scopes.
         * @enum {string}
         */
        Scope: "render" | "manage" | "credentials";
        /**
         * TargetKind
         * @description What a mapping rule writes into the pass.
         * @enum {string}
         */
        TargetKind: "field_value" | "field_label" | "barcode_message" | "barcode_alt_text" | "image" | "nfc_payload" | "json_pointer";
        /**
         * TemplateResponse
         * @description Response describing a template.
         */
        TemplateResponse: {
            /** Archived At */
            archived_at?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Description */
            description?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Key */
            key: string;
            /** Name */
            name: string;
        };
        /**
         * TenantIn
         * @description A tenant to create.
         */
        TenantIn: {
            /** Key */
            key: string;
            /** Name */
            name: string;
        };
        /**
         * TenantOut
         * @description A tenant as the UI shows it.
         */
        TenantOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Key */
            key: string;
            /** Name */
            name: string;
        };
        /**
         * UpdateTemplateRequest
         * @description Request body to patch a template's name or description.
         */
        UpdateTemplateRequest: {
            /** Description */
            description?: string | null;
            /** Name */
            name?: string | null;
        };
        /**
         * UpdateVariantRequest
         * @description Request body to patch a variant's default flag or credential/class id.
         */
        UpdateVariantRequest: {
            /** Credential Set Id */
            credential_set_id?: string | null;
            /** Google Class Id */
            google_class_id?: string | null;
            /** Is Default */
            is_default?: boolean | null;
            /** Name */
            name?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * ValidationResponse
         * @description Response describing the outcome of a (non-publishing) validation run.
         */
        ValidationResponse: {
            /**
             * Findings
             * @default []
             */
            findings: string[];
            /** Valid */
            valid: boolean;
        };
        /**
         * ValueType
         * @description Type of the value a mapping rule binds.
         * @enum {string}
         */
        ValueType: "text" | "date" | "number" | "boolean" | "image" | "uri";
        /**
         * VariantResponse
         * @description Response describing a template variant.
         */
        VariantResponse: {
            /** Archived At */
            archived_at?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Credential Set Id */
            credential_set_id?: string | null;
            /** Google Class Id */
            google_class_id?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Is Default */
            is_default: boolean;
            /** Key */
            key: string;
            /** Name */
            name: string;
            /**
             * Template Id
             * Format: uuid
             */
            template_id: string;
            wallet_type: components["schemas"]["WalletType"];
        };
        /**
         * VersionResponse
         * @description Response describing a template version.
         */
        VersionResponse: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Nfc Enabled */
            nfc_enabled: boolean;
            /** Nfc Encryption Public Key */
            nfc_encryption_public_key?: string | null;
            /**
             * Nfc Requires Authentication
             * @default false
             */
            nfc_requires_authentication: boolean;
            /** Notes */
            notes?: string | null;
            /** Number */
            number: number;
            /** Published At */
            published_at?: string | null;
            status: components["schemas"]["VersionStatus"];
            /**
             * Variant Id
             * Format: uuid
             */
            variant_id: string;
        };
        /**
         * VersionStatus
         * @description Lifecycle state of a template version.
         * @enum {string}
         */
        VersionStatus: "draft" | "published" | "archived";
        /**
         * WalletType
         * @description Which wallet technology a pass was issued for.
         * @enum {string}
         */
        WalletType: "GOOGLE_ST" | "GOOGLE_ACCESS" | "GOOGLE_IDENTITY" | "APPLE_VAS" | "APPLE_ACCESS" | "APPLE_IDENTITY" | "SAMSUNG_ST" | "SAMSUNG_ACCESS" | "SAMSUNG_IDENTITY" | "EUDI_PASS";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_tenants_api_v1_tenants_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenantOut"][];
                };
            };
        };
    };
    create_tenant_api_v1_tenants_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TenantIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenantOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_audit_api_v1_tenants__tenant_id__audit_get: {
        parameters: {
            query?: {
                from_?: string | null;
                to?: string | null;
                template?: string | null;
                subject_ref?: string | null;
                outcome?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                tenant_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditEntryResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_clients_api_v1_tenants__tenant_id__clients_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiClientOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_client_api_v1_tenants__tenant_id__clients_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApiClientIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiClientCreated"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revoke_client_api_v1_tenants__tenant_id__clients__client_id__revoke_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant_id: string;
                client_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_credentials_api_v1_tenants__tenant_id__credentials_get: {
        parameters: {
            query?: {
                provider?: components["schemas"]["Provider"] | null;
                expiring_within?: string | null;
            };
            header?: never;
            path: {
                tenant_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CredentialResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_credential_api_v1_tenants__tenant_id__credentials_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCredentialRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CredentialResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revoke_credential_api_v1_tenants__tenant_id__credentials__credential_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                credential_id: string;
                tenant_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    install_certificate_api_v1_tenants__tenant_id__credentials__credential_id__certificate_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                credential_id: string;
                tenant_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InstallCertificateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CredentialResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_csr_api_v1_tenants__tenant_id__credentials__credential_id__csr_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                credential_id: string;
                tenant_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    renew_credential_api_v1_tenants__tenant_id__credentials__credential_id__renew_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                credential_id: string;
                tenant_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CredentialResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_fields_api_v1_tenants__tenant_id__fields_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FieldResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_catalogue_api_v1_tenants__tenant_id__fields_catalogue_json_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CatalogueExport"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_fields_api_v1_tenants__tenant_id__fields_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FieldResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_templates_api_v1_tenants__tenant_id__templates_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TemplateResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_template_api_v1_tenants__tenant_id__templates_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTemplateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TemplateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_template_api_v1_tenants__tenant_id__templates__template_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                template_id: string;
                tenant_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TemplateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    archive_template_api_v1_tenants__tenant_id__templates__template_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                template_id: string;
                tenant_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TemplateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_template_api_v1_tenants__tenant_id__templates__template_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                template_id: string;
                tenant_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateTemplateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TemplateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_variants_api_v1_tenants__tenant_id__templates__template_id__variants_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                template_id: string;
                tenant_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VariantResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_variant_api_v1_tenants__tenant_id__templates__template_id__variants_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                template_id: string;
                tenant_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateVariantRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VariantResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_variant_api_v1_tenants__tenant_id__variants__variant_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                variant_id: string;
                tenant_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VariantResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_variant_api_v1_tenants__tenant_id__variants__variant_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                variant_id: string;
                tenant_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateVariantRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VariantResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sync_variant_api_v1_tenants__tenant_id__variants__variant_id__sync_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                variant_id: string;
                tenant_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_versions_api_v1_tenants__tenant_id__variants__variant_id__versions_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                variant_id: string;
                tenant_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_version_api_v1_tenants__tenant_id__variants__variant_id__versions_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                variant_id: string;
                tenant_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_version_api_v1_tenants__tenant_id__versions__version_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                version_id: string;
                tenant_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_asset_api_v1_tenants__tenant_id__versions__version_id__assets__filename__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                version_id: string;
                filename: string;
                tenant_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_asset_api_v1_tenants__tenant_id__versions__version_id__assets__filename__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                version_id: string;
                filename: string;
                tenant_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_asset_api_v1_tenants__tenant_id__versions__version_id__assets__filename__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                version_id: string;
                filename: string;
                tenant_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_mappings_api_v1_tenants__tenant_id__versions__version_id__mappings_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                version_id: string;
                tenant_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MappingRulesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_mappings_api_v1_tenants__tenant_id__versions__version_id__mappings_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                version_id: string;
                tenant_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MappingRulesRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MappingRulesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    publish_version_api_v1_tenants__tenant_id__versions__version_id__publish_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                version_id: string;
                tenant_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    validate_version_api_v1_tenants__tenant_id__versions__version_id__validate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                version_id: string;
                tenant_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    readyz_readyz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
